# Generated by Django 2.1.7 on 2019-10-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FILE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(blank=True, max_length=264, null=True)),
                ('Product_URL', models.URLField(blank=True, null=True)),
                ('Reviews', models.FloatField(blank=True, null=True)),
                ('Review_Count', models.PositiveIntegerField(blank=True, null=True)),
                ('Price', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('Image_URL', models.URLField(blank=True, null=True)),
                ('Category', models.CharField(blank=True, max_length=64, null=True)),
                ('Sub_Category', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
